### ISSUE TITLE
style.less source

### ISSUE THREAD

**Issue by adambene** [layerhq/layer-js-sampleapps#12]
It would be really nice to have the style.less source file or whatever preprocessor you use.

Thanks!

**Comment by nilgradisnik** [comment]
The CSS that's part of this repository is more of a quick and simple theme to serve the sample app purpose only and it's not intended to be extendable.

We are planning on releasing a UI framework that will contain a more polished CSS which you will be able to extend, similarly to our [Atlas](https://atlas.layer.com) for mobile.

**Comment by adambene** [comment]
That would be even better. :)
When do you plan that release?

**Comment by michaelkantor** [comment]
We aren't at a point where we can commit to anything; a beta arriving mid-summer is what we're hoping for.
