### ISSUE TITLE
Publish layer-react on npm

### ISSUE THREAD

**Issue by axelson** [layerhq/layer-js-sampleapps#15]
Hi,
Do you have plans to publish layer-react on npm? It would help when bundling with webpack. Otherwise what is the recommended approach to include layer-react in a project?

**Comment by michaelkantor** [comment]
The plans are for us to wait for sufficient number of developers comfortable in the React/Redux philosophy to comment on this being consistent with the React/Redux philosophy and an effective implementation/mechanism for working with the Layer WebSDK before we publish and support it.

So: if you have reviewed it, please comment on it here; we will leave this ticket open in hopes that others will comment on this ticket as well.

**Comment by axelson** [comment]
Okay, that makes sense. I will comment on here after reviewing the API more throughly.

**Comment by yangmillstheory** [comment]
Any updates on NPM publishing? I don't see an alternative to using this in my company's project other than forking and publishing ourselves (to our private registry), or manually checking the code into our VCS.

**Comment by michaelkantor** [comment]
Sadly, the comments you see above is all the feedback we've received so far.  We'll try publishing this as a separate npm repo to see if that gives us better feedback.

**Comment by yangmillstheory** [comment]
Sounds good.

We'll be using this heavily in one of our nascent apps, so I'll keep in mind that feedback is desired.

**Comment by atwoodjw** [comment]
Ditto. The React sample code features prominently in a webapp we're building. Ultimately, having something more akin to Atlas (iOS, Android) for web seems like the way to go.

**Comment by yangmillstheory** [comment]
Just wanted to say though, 10K-foot view after combing through the code a bit, the code itself is pretty well-crafted and JS-documented.

**Comment by nilgradisnik** [comment]
Published [layer-react](https://www.npmjs.com/package/layer-react).
