### ISSUE TITLE
Can't start web UI sample app

### ISSUE THREAD

**Issue by gregdingle** [layerhq/layer-js-sampleapps#26]
I want to get the react web ui sample app working. I got the react web sdk app running no problem by following the readme. 

I open the app in my localhost.

![image](https://cloud.githubusercontent.com/assets/28797/21352589/7fb90e4c-c6c2-11e6-9779-c4e4f1745c8b.png)

But then the buttons don't work and I get these errors in the console:
![image](https://cloud.githubusercontent.com/assets/28797/21352521/2627e25e-c6c2-11e6-94da-3cee28e85783.png)

There are no CSS files in my `node_modules`, only LESS files of the same name, so I guess I'm missing some undocumented build step. I'm new to node so I'm missing something basic.

**Comment by michaelkantor** [comment]
Update has been published to npm.

**Comment by gregdingle** [comment]
@michaelkantor sorry but I couldn't grasp what the fix I need is here. I `git pull`, `npm install` again, but I get the same issue.

**Comment by michaelkantor** [comment]
`npm install layer-ui-web --save` should update you to the latest.  If not, `rm -rf node_modules/layer-ui-web` and then retry `npm install`.  If your using `git pull` then your doing something unexpected here.

**Comment by gregdingle** [comment]
It works now  😄  thanks!
