### ISSUE TITLE
createMessage with UTF-8

### ISSUE THREAD

**Issue by lethanhquang** [layerhq/layer-js-sampleapps#7]
Hello,
I'm from VietNam, and I'm using `layer-react` to build the chat application on web. My issue is when I send new message via layer-client-sdk It doesn't display right encoding. 

After looking on the layer-client-sdk code, I found new way to custom encoding for the MessageParts:

```
    const conversationURL = `layer:///conversations/${state.router.params.conversationId}`;
    const conversation = layerClient.getConversation(conversationURL, true);

    conversation.createMessage({
      parts: [{
        body: "Tôi là người Việt Nam",
        encoding: 'utf-8'
      }],
    }).send();
```

But... it still not working.

Could you please give me some ideas?

**Comment by michaelkantor** [comment]
There is a known issue with our websocket server for handling these.  What your doing should work as-is.  The work around until this has been fixed is to send this as a base64 encoded message; see if the following works for you:
```
 var body = btoa(unescape(encodeURIComponent("Tôi là người Việt Nam")));
 conversation.createMessage({
      parts: [{
        body: body,
        encoding: 'base64'
      }],
    }).send();
```
On receiving messages you'll need to check if its base64 encoded and if it is: 
```
var text = part.encoding === "base64" ? decodeURIComponent(escape(atob(part.body))) : part.body;
```

Michael

**Comment by lethanhquang** [comment]
Thank @michaelkantor It's worked!
